" Vim color file
"   This file was generated by Palette
"   http://rubygems.org/gems/palette
"
" Author: Sterling Cobb
" Notes:  This is a WIP

hi clear
if version > 580
    if exists("syntax_on")
        syntax reset
    endif
endif

let colors_name="sterling-colors"

if has("gui_running")
    set background=dark
endif
